### ISSUE TITLE
[BUG] Hair styles not appearing on character

### ISSUE THREAD

**Issue by Luke1215** [Rage-GitHub/Modding-Lounge#10]
## What Issue is Occurring?
Hair isn't showing up on character in CC or in-game. Every character bald

## Where/When/How is This Issue Happening?
During CC no hair styles were available and even in-game your selections aren't loaded

## Have You Modified The Modlist In Anyway?
<sup>Select Only One Option, I.E. fill [ ] with an X</sup>
- [x ] No, I have not touched the modlist
- [ ] Yes, I've edited it somewhat
- [ ] Yes, I've made significant changes to the modlist

## Were You Able to Replicate This Issue?
<sup>Select Only One Option, I.E. fill [ ] with an X</sup>
- [x ] Yes, I've successfully replicated the issue
- [ ] No, it was a one-time thing

## Other Information
**Modlist Version**
> 2.2.0

**Game Version**
> Current Steam Release

**Is The Modlist Installed on the Same Drive?**
<sup>Select Only One Option, I.E. fill [ ] with an X</sup>
- [ x] Yes, it's installed in the same drive
- [ ] No, it's installed on a different drive

**Is Your Game Installation Outside of Protected Folders, I.E. Program Files (x86)?**
<sup>Select Only One Option, I.E. fill [ ] with an X</sup>
- [ x] Yes, it's installed outside of a protected folder
- [ ] No, it's not installed outside of a protected folder

**What Are Your PC Specs?**
CPU: R7 7700X
RAM: HyperX Fury DDDR5 6000 CL30
SSD (The one both the modlist and the game are installed to): Samsung Pro EVO 970
GPU: Radeon RX 7900XTX

**Comment by Rage-GitHub** [comment]
It seems you have an AMD GPU, make sure you download [DXVK](https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=1000125704&nmm=1&game_id=130) to fix this issue.
