### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ghost** [Rage-GitHub/Modding-Lounge#6]
## What Issue is Occurring?
*White screen and crashing after character creation. Also side note... game crashed after hitting start at the main menu and was automatically sent to nexus. Had to add a line and subtract something else in the fallout.ini. Used MO2 to do so. Here's the link to the page I was sent to. Something for archive invalidation.
https://www.nexusmods.com/fallout4/mods/4421

## Where/When/How is This Issue Happening?
The white screen and crashing is at the beginning of the game after character creation. I think it's due to the amount of mods loading in alongside start me up redux loading. 

## Have You Modified The Modlist In Anyway?
<sup>Select Only One Option, I.E. fill [ ] with an X</sup>
- [X] No, I have not touched the modlist
- [ ] Yes, I've edited it somewhat
- [ ] Yes, I've made significant changes to the modlist

### If you've made changes, what mods/changes have you added/removed?
N/A

## Were You Able to Replicate This Issue?
<sup>Select Only One Option, I.E. fill [ ] with an X</sup>
- [X] Yes, I've successfully replicated the issue
- [ ] No, it was a one-time thing

## Other Information
**Modlist Version**
> 1.6.0 on wabbajack.

**Game Version**
> steam current version

**Is The Modlist Installed on the Same Drive?**
<sup>Select Only One Option, I.E. fill [ ] with an X</sup>
- [X] Yes, it's installed in the same drive
- [ ] No, it's installed on a different drive

**Is Your Game Installation Outside of Protected Folders, I.E. Program Files (x86)?**
<sup>Select Only One Option, I.E. fill [ ] with an X</sup>
- [X] Yes, it's installed outside of a protected folder
- [ ] No, it's not installed outside of a protected folder

**What Are Your PC Specs?**
1080ti, i7 6700, 2x 512 gb ssd's, 16 gb 3200 MHz Ram. 1440p 144hz gsync monitor (game capped at 100 fps).

**Comment by Rage-GitHub** [comment]
Usually, the best solution for this issue is to save the game, close it out, then reload that save and wait for the mods to finish loading.
