### ISSUE TITLE
the WP Configuration page is blank, there is no instructions 

### ISSUE THREAD

**Issue by lovemetal626** [Rage-GitHub/Modding-Lounge#8]
Hi, I think the WP configuration page was deleted in error possibly? when you click on it, its blank, there is no instructions on how to configure the modlist.

**Comment by CheesusChrist15** [comment]
+1, would like to be able to know if i'm missing anything

**Comment by nekomancer03** [comment]
ditto, i want to play with this list but i cant if the documentation isnt complete to begin with

**Comment by Spamerton** [comment]
This does work, but it's a pain.  (I am not the author, just trying to help, I'm not going to answer any questions, just offer these suggestions)

0. Start Skyrim SE and download all creation kit content if you don't have it.
1. Make a backup copy of your Skyrim SE install folder.
2. Validate the files through steam
3. Downgrade your Skyrim install to 1.6.1130.  (Google this, it involves using the steam console)
4. Delete your ccbgssse037-curios.esl and ccbgssse037-curios.bsa in your data folder.
5. Get the compatible version of curios by Starting downgraded SkyrimSE and manually log into the creation club, download the creation club curios from there (get the actual file, not a patch, that will get the correct version)
6. Finally, in Steam, install the Special Edition Creation kit.
7. Good Luck!
8. Once it is installed, you can revert your skyrim install folder to your orginal version.

**Comment by Spamerton** [comment]
One final thing, downgrade wabbajack to 3.4.0.0 by downloading it from their github site and running the executable in the extracted folder, or you might get a hash error.
